### ISSUE TITLE
Doesn't work for destructuring

### ISSUE THREAD

**Issue by vjpr** [jameswomack/replace-require-with-import#3]
```
const {createStore} = require('redux')
```

**Comment by jameswomack** [comment]
@vjpr thank you for opening this issue. I'll take a look and get 'er fixed.

**Comment by jameswomack** [comment]
FWIW, I created the module for a very specific use case that didn't include that `import` style, but I do want folks who come across this to be able to use this for all cases now.

**Comment by vjpr** [comment]
Thanks that would be great.

I am using it as an "External tool" in Webstorm with a keyboard shortcut.
Saves me a lot of time.

**Comment by jameswomack** [comment]
@vjpr I released 2.1.0 in an effort to support `const {createStore} = require('redux')`. I added tests for the various cases but they only run in a Unix-like environment. The module will work anywhere though.
